### ISSUE TITLE
exit from config mode back to privileged mode

### ISSUE THREAD

**Issue by smytht** [yellowman/nsh#66]
cant exit from config mode to privileged mode
not a big issue quit works but it quits the shell
it can be useful from a user point of view / safety point of view to be only in config mode for config work
but keep the shell open and be able to run privileged show commands for diagnostics / montioring puroposes ...

**Comment by yellowman** [comment]
So, this is probably more of a bad syntax issue

To leave privileged mode, instead of 'enable' you 'disable' (the 'enable command' doesn't take a 'no' argument)

However, the configure command takes a 'no' argument, 'no config' for instance

To be more cisco-like, it could take ^Z to exit configure mode. In fact, I already wanted to do that for 'interface' mode before we actually had configure mode but I haven't figured out how to get ^Z to work as a libedit binding yet, probably have to figure out how to take it away from the job control side of things first?

**Comment by smytht** [comment]
yes
no configure
command works  we will review the syntax as part of our usability... so the issue was my understanding of the current implementation....
